//! The generated Cargo workspace (docs/spec/build.md, "Generated workspace").

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use pwc_manifest::{LockedPackage, Lockfile, ModKind, PackageId};
use toml::{Table, Value};

use crate::source::{API_DIR, PwcSourceInfo, RUNTIME_PACKAGE};
use crate::{
    BUNDLE_PACKAGE, BuildError, BuildRequest, GAME_BIN, GOLDEN_BIN, GeneratedWorkspace,
    INSTANCE_PACKAGE, absolute, io_err,
};

/// The header every generated file starts with.
const HEADER: &str = "Generated by pwc. Do not edit.";

/// Crate names a package may not take: they would clash with the crates the build links.
const RESERVED_CRATE_NAMES: &[&str] = &[
    RUNTIME_PACKAGE,
    "pwc_mod_api",
    "pwc_bundle",
    "pwc_game_instance",
];

/// The lock file name inside the generated workspace; written only when absent (Cargo owns it).
pub(crate) const CARGO_LOCK: &str = "Cargo.lock";

/// One package that gets a crate (`kind = "mod"` or `"library"`).
struct CratePlan<'a> {
    package: &'a LockedPackage,
    crate_name: String,
    lib_path: String,
    edition: &'static str,
    /// Crate names of its mod/library dependencies, sorted.
    deps: Vec<String>,
}

pub(crate) fn generate(request: &BuildRequest) -> Result<GeneratedWorkspace, BuildError> {
    let lock = &request.lock;
    let pwc_dir = absolute(&request.pwc_source)?;
    let info = PwcSourceInfo::read(&pwc_dir)?;
    info.check_against(lock)?;

    let order = registration_order(lock)?;
    let crate_names = crate_names(lock)?;
    let kinds: BTreeMap<&PackageId, ModKind> =
        lock.packages.iter().map(|p| (&p.id, p.kind)).collect();

    let mut plans = Vec::new();
    for package in &lock.packages {
        let (dir, manifest) = request.packages.get(&package.id).ok_or_else(|| {
            BuildError::Package(
                package.id.clone(),
                "not in the store (run `pwc lock`)".into(),
            )
        })?;
        if manifest.id() != &package.id
            || manifest.version() != &package.version
            || manifest.kind() != package.kind
        {
            return Err(BuildError::Package(
                package.id.clone(),
                format!(
                    "store entry is {} {} ({}) but the lock says {} {} ({})",
                    manifest.id(),
                    manifest.version(),
                    manifest.kind().as_str(),
                    package.id,
                    package.version,
                    package.kind.as_str()
                ),
            ));
        }
        if package.kind == ModKind::Bundle {
            continue;
        }
        match &manifest.package.pwc_api {
            Some(req) if req.matches(&lock.pwc.api) => {}
            Some(req) => {
                return Err(BuildError::Package(
                    package.id.clone(),
                    format!(
                        "requires pwc-api {req} but this PWC provides {}",
                        lock.pwc.api
                    ),
                ));
            }
            None => {
                return Err(BuildError::Package(
                    package.id.clone(),
                    "has no pwc-api requirement".into(),
                ));
            }
        }
        let deps = package
            .dependencies
            .iter()
            .filter(|d| kinds.get(d).is_some_and(|k| *k != ModKind::Bundle))
            .map(|d| crate_names[d].clone())
            .collect::<BTreeSet<_>>()
            .into_iter()
            .collect();
        let lib = absolute(&dir.join("src").join("lib.rs"))?;
        plans.push(CratePlan {
            package,
            crate_name: crate_names[&package.id].clone(),
            lib_path: utf8(&lib)?.to_owned(),
            edition: manifest.package.edition.as_str(),
            deps,
        });
    }
    plans.sort_by(|a, b| a.crate_name.cmp(&b.crate_name));

    let api_path = API_DIR.iter().fold(pwc_dir.clone(), |p, c| p.join(c));
    let api_path = utf8(&api_path)?;
    let pwc_path = utf8(&pwc_dir)?;

    let mut files = BTreeMap::new();
    let mut members = vec!["bundle".to_owned(), "instance".to_owned()];
    members.extend(plans.iter().map(|p| format!("mods/{}", p.crate_name)));
    files.insert(
        "Cargo.toml".to_owned(),
        root_manifest(&info, &members, &pwc_dir)?,
    );
    if let Some(seed) = &info.cargo_lock {
        files.insert(CARGO_LOCK.to_owned(), seed.clone());
    }
    for plan in &plans {
        files.insert(
            format!("mods/{}/Cargo.toml", plan.crate_name),
            mod_manifest(plan, api_path),
        );
    }

    let mods: Vec<&LockedPackage> = order
        .into_iter()
        .filter(|p| p.kind == ModKind::Mod)
        .collect();
    let mod_crates: Vec<&str> = mods.iter().map(|p| crate_names[&p.id].as_str()).collect();
    files.insert(
        "bundle/Cargo.toml".to_owned(),
        bundle_manifest(api_path, &mod_crates),
    );
    let mut descriptors = Vec::new();
    for &package in &mods {
        let name = &request.packages[&package.id].1.package.name;
        descriptors.push((package, name.as_str(), crate_names[&package.id].as_str()));
    }
    files.insert(
        "bundle/src/lib.rs".to_owned(),
        bundle_lib(&lock.environment, &descriptors),
    );
    files.insert(
        "instance/Cargo.toml".to_owned(),
        instance_manifest(pwc_path),
    );
    files.insert(
        format!("instance/src/bin/{GAME_BIN}.rs"),
        bin_main("project_watt_cubed::run"),
    );
    files.insert(
        format!("instance/src/bin/{GOLDEN_BIN}.rs"),
        bin_main("project_watt_cubed::harness::golden_main"),
    );
    Ok(GeneratedWorkspace { files })
}

/// Every package in the lock in registration order: a topological order over the lock's
/// dependency edges (dependencies first), ties broken by id.
pub(crate) fn registration_order(lock: &Lockfile) -> Result<Vec<&LockedPackage>, BuildError> {
    let by_id: BTreeMap<&PackageId, &LockedPackage> =
        lock.packages.iter().map(|p| (&p.id, p)).collect();
    if by_id.len() != lock.packages.len() {
        return Err(BuildError::Lock(
            "a package id appears more than once".into(),
        ));
    }
    let mut pending: BTreeMap<&PackageId, usize> = BTreeMap::new();
    let mut dependents: BTreeMap<&PackageId, Vec<&PackageId>> = BTreeMap::new();
    for package in &lock.packages {
        let deps: BTreeSet<&PackageId> = package.dependencies.iter().collect();
        for dep in &deps {
            if !by_id.contains_key(dep) {
                return Err(BuildError::Lock(format!(
                    "{} depends on {dep}, which is not in the lock",
                    package.id
                )));
            }
            dependents.entry(dep).or_default().push(&package.id);
        }
        pending.insert(&package.id, deps.len());
    }
    let mut ready: BTreeSet<&PackageId> = pending
        .iter()
        .filter(|(_, n)| **n == 0)
        .map(|(id, _)| *id)
        .collect();
    let mut order = Vec::with_capacity(lock.packages.len());
    while let Some(id) = ready.pop_first() {
        order.push(by_id[id]);
        for dependent in dependents.get(id).into_iter().flatten() {
            let n = pending
                .get_mut(dependent)
                .expect("every dependent is a lock package");
            *n -= 1;
            if *n == 0 {
                ready.insert(dependent);
            }
        }
    }
    if order.len() != lock.packages.len() {
        let stuck: Vec<String> = pending
            .iter()
            .filter(|(_, n)| **n > 0)
            .map(|(id, _)| id.to_string())
            .collect();
        return Err(BuildError::Lock(format!(
            "dependency cycle among {}",
            stuck.join(", ")
        )));
    }
    Ok(order)
}

/// Crate name of every package that gets a crate; rejects clashes (`a.b-c` vs `a.b.c`) and the
/// names of the crates every build links.
fn crate_names(lock: &Lockfile) -> Result<BTreeMap<PackageId, String>, BuildError> {
    let mut names = BTreeMap::new();
    let mut taken: BTreeMap<String, &PackageId> = BTreeMap::new();
    for package in lock.packages.iter().filter(|p| p.kind != ModKind::Bundle) {
        let name = package.id.crate_name();
        if RESERVED_CRATE_NAMES.contains(&name.as_str()) {
            return Err(BuildError::Package(
                package.id.clone(),
                format!("crate name `{name}` is reserved by the build"),
            ));
        }
        if let Some(other) = taken.insert(name.clone(), &package.id) {
            return Err(BuildError::Lock(format!(
                "{other} and {} have the same crate name `{name}`",
                package.id
            )));
        }
        names.insert(package.id.clone(), name);
    }
    Ok(names)
}

/// The workspace root: members, the PWC root's resolver, and its `[profile.*]` / `[patch.*]`
/// tables (patch paths made absolute) so the build matches a vanilla build exactly.
fn root_manifest(
    info: &PwcSourceInfo,
    members: &[String],
    pwc_dir: &Path,
) -> Result<String, BuildError> {
    let mut s = format!(
        "# {HEADER}\n# [profile.*] and [patch.*] are copied from the PWC source's Cargo.toml.\n\n[workspace]\nresolver = {}\nmembers = [\n",
        toml_str(info.resolver())
    );
    for member in members {
        let _ = writeln!(s, "    {},", toml_str(member));
    }
    s.push_str("]\n");
    let mut copied = Table::new();
    if let Some(profile) = info.root.get("profile") {
        copied.insert("profile".to_owned(), profile.clone());
    }
    if let Some(patch) = info.root.get("patch") {
        copied.insert("patch".to_owned(), absolutize_patch(patch, pwc_dir)?);
    }
    if !copied.is_empty() {
        let text = toml::to_string(&copied).map_err(|e| {
            BuildError::Source(format!("cannot copy [profile]/[patch] tables: {e}"))
        })?;
        s.push('\n');
        s.push_str(&text);
        if !s.ends_with('\n') {
            s.push('\n');
        }
    }
    Ok(s)
}

/// `[patch.<registry>.<crate>] path = "…"` entries made absolute against the PWC root.
fn absolutize_patch(patch: &Value, pwc_dir: &Path) -> Result<Value, BuildError> {
    let mut patch = patch.clone();
    if let Value::Table(registries) = &mut patch {
        for (_, registry) in registries.iter_mut() {
            let Value::Table(crates) = registry else {
                continue;
            };
            for (_, spec) in crates.iter_mut() {
                let Value::Table(spec) = spec else { continue };
                if let Some(Value::String(path)) = spec.get_mut("path") {
                    let joined = pwc_dir.join(&*path);
                    *path = utf8(&joined)?.to_owned();
                }
            }
        }
    }
    Ok(patch)
}

fn mod_manifest(plan: &CratePlan<'_>, api_path: &str) -> String {
    let p = plan.package;
    let mut s = format!(
        "# {HEADER}\n# {} {} ({})\n[package]\nname = {}\nversion = {}\nedition = {}\npublish = false\n{}\n[lib]\npath = {}\n\n[dependencies]\npwc-mod-api = {{ path = {} }}\n",
        p.id,
        p.version,
        p.hash,
        toml_str(&plan.crate_name),
        toml_str(&p.version.to_string()),
        toml_str(plan.edition),
        NO_AUTO_TARGETS,
        toml_str(&plan.lib_path),
        toml_str(api_path),
    );
    for dep in &plan.deps {
        let _ = writeln!(s, "{dep} = {{ path = {} }}", toml_str(&format!("../{dep}")));
    }
    s
}

/// Target auto-discovery off: the generated package directories hold only `Cargo.toml`.
const NO_AUTO_TARGETS: &str =
    "autobins = false\nautoexamples = false\nautotests = false\nautobenches = false\n";

fn bundle_manifest(api_path: &str, mod_crates: &[&str]) -> String {
    let mut sorted: Vec<&str> = mod_crates.to_vec();
    sorted.sort_unstable();
    let mut s = format!(
        "# {HEADER}\n[package]\nname = {}\nversion = \"0.0.0\"\nedition = \"2024\"\npublish = false\n{NO_AUTO_TARGETS}\n[lib]\nname = \"pwc_bundle\"\npath = \"src/lib.rs\"\n\n[dependencies]\npwc-mod-api = {{ path = {} }}\n",
        toml_str(BUNDLE_PACKAGE),
        toml_str(api_path),
    );
    for name in sorted {
        let _ = writeln!(
            s,
            "{name} = {{ path = {} }}",
            toml_str(&format!("../mods/{name}"))
        );
    }
    s
}

fn bundle_lib(environment: &str, mods: &[(&LockedPackage, &str, &str)]) -> String {
    let mut s = format!(
        "//! {HEADER}\n\n/// The environment hash of the lock this bundle was generated from.\npub const ENVIRONMENT: &str = {};\n\n/// The game build: every `kind = \"mod\"` package, dependencies before dependents, ties by id.\npub fn game_build() -> pwc_mod_api::GameBuild {{\n    pwc_mod_api::GameBuild::new()\n        .with_environment(ENVIRONMENT)",
        rust_str(environment)
    );
    for (package, name, crate_name) in mods {
        let _ = write!(
            s,
            "\n        .with_mod(pwc_mod_api::ModDescriptor {{\n            id: {}, name: {}, version: {},\n            register: {crate_name}::register,\n        }})",
            rust_str(package.id.as_str()),
            rust_str(name),
            rust_str(&package.version.to_string()),
        );
    }
    s.push_str("\n}\n");
    s
}

fn instance_manifest(pwc_path: &str) -> String {
    format!(
        "# {HEADER}\n[package]\nname = {}\nversion = \"0.0.0\"\nedition = \"2024\"\npublish = false\n{NO_AUTO_TARGETS}\n[[bin]]\nname = {}\npath = {}\n\n[[bin]]\nname = {}\npath = {}\n\n[dependencies]\n{RUNTIME_PACKAGE} = {{ path = {} }}\n{BUNDLE_PACKAGE} = {{ path = \"../bundle\" }}\n",
        toml_str(INSTANCE_PACKAGE),
        toml_str(GAME_BIN),
        toml_str(&format!("src/bin/{GAME_BIN}.rs")),
        toml_str(GOLDEN_BIN),
        toml_str(&format!("src/bin/{GOLDEN_BIN}.rs")),
        toml_str(pwc_path),
    )
}

fn bin_main(entry: &str) -> String {
    format!("//! {HEADER}\n\nfn main() {{\n    {entry}(pwc_bundle::game_build());\n}}\n")
}

/// Every mod/library store directory must hold its `src/lib.rs`.
pub(crate) fn check_store_dirs(request: &BuildRequest) -> Result<(), BuildError> {
    for package in &request.lock.packages {
        let Some((dir, _)) = request.packages.get(&package.id) else {
            return Err(BuildError::Package(
                package.id.clone(),
                "not in the store (run `pwc lock`)".into(),
            ));
        };
        if !dir.is_dir() {
            return Err(BuildError::Package(
                package.id.clone(),
                format!("store directory {} is missing", dir.display()),
            ));
        }
        if package.kind != ModKind::Bundle && !dir.join("src").join("lib.rs").is_file() {
            return Err(BuildError::Package(
                package.id.clone(),
                format!(
                    "store directory {} has no src/lib.rs (run `pwc store verify`)",
                    dir.display()
                ),
            ));
        }
    }
    Ok(())
}

/// Write the generated files under `dir`. Unchanged files are left alone (their mtimes are part
/// of Cargo's fingerprints), `Cargo.lock` is only seeded when absent, and crate directories
/// under `mods/` that are no longer generated are removed.
pub(crate) fn write_workspace(
    dir: &Path,
    workspace: &GeneratedWorkspace,
) -> Result<(), BuildError> {
    std::fs::create_dir_all(dir).map_err(io_err(dir))?;
    let mods_dir = dir.join("mods");
    let wanted: BTreeSet<&str> = workspace
        .files
        .keys()
        .filter_map(|k| {
            k.strip_prefix("mods/")
                .and_then(|rest| rest.split('/').next())
        })
        .collect();
    if mods_dir.is_dir() {
        for entry in std::fs::read_dir(&mods_dir).map_err(io_err(&mods_dir))? {
            let entry = entry.map_err(io_err(&mods_dir))?;
            let keep = entry
                .file_name()
                .to_str()
                .is_some_and(|n| wanted.contains(n));
            if !keep {
                let path = entry.path();
                std::fs::remove_dir_all(&path).map_err(io_err(&path))?;
            }
        }
    }
    for (rel, contents) in &workspace.files {
        let path: PathBuf = rel.split('/').fold(dir.to_path_buf(), |p, c| p.join(c));
        if rel == CARGO_LOCK && path.exists() {
            continue;
        }
        match std::fs::read(&path) {
            Ok(existing) if existing == contents.as_bytes() => continue,
            _ => {}
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(io_err(parent))?;
        }
        std::fs::write(&path, contents).map_err(io_err(&path))?;
    }
    Ok(())
}

/// A path as UTF-8 (Cargo manifests and generated sources are UTF-8).
fn utf8(path: &Path) -> Result<&str, BuildError> {
    path.to_str()
        .ok_or_else(|| BuildError::Source(format!("path {} is not valid UTF-8", path.display())))
}

/// A TOML basic string: `"`, `\` and control characters escaped.
pub(crate) fn toml_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c if c.is_control() => {
                let _ = write!(out, "\\u{:04X}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// A Rust string literal: printable ASCII as is (`"` and `\` escaped), everything else as
/// `\u{…}`, so no name can smuggle control or bidirectional-override characters into source.
pub(crate) fn rust_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            ' '..='~' => out.push(c),
            c => {
                let _ = write!(out, "\\u{{{:x}}}", c as u32);
            }
        }
    }
    out.push('"');
    out
}
