//! `build.toml`: what a build directory holds and whether it finished.

use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use crate::{
    BUILDER_VERSION, BuildError, BuildRequest, GAME_BIN, GOLDEN_BIN, PreparedBuild, exe_name,
    io_err,
};

/// The metadata file name inside a build directory.
pub(crate) const FILE: &str = "build.toml";

/// `build.toml` (format 1).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub(crate) struct BuildMetadata {
    pub format: u32,
    pub build_id: String,
    pub environment: String,
    pub profile: String,
    pub target: String,
    pub builder: String,
    pub rustc: String,
    pub generated: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub finished: Option<String>,
    pub pwc: PwcMetadata,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Outputs>,
    #[serde(default)]
    pub package: Vec<PackageMetadata>,
}

/// `[pwc]`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub(crate) struct PwcMetadata {
    pub source: String,
    pub version: String,
    pub api: String,
    pub revision: String,
    pub dirty_digest: String,
}

/// `[outputs]`, present once the build finished.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct Outputs {
    pub game: String,
    pub golden: String,
}

/// One `[[package]]` input.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct PackageMetadata {
    pub id: String,
    pub version: String,
    pub kind: String,
    pub hash: String,
    pub dir: String,
}

/// Whether `prepared.dir` holds a finished build of exactly `prepared.build_id`.
pub(crate) fn is_finished(prepared: &PreparedBuild) -> bool {
    let Ok(text) = std::fs::read_to_string(prepared.dir.join(FILE)) else {
        return false;
    };
    let Ok(meta) = toml::from_str::<BuildMetadata>(&text) else {
        return false;
    };
    meta.build_id == prepared.build_id
        && meta.finished.is_some()
        && prepared.game().is_file()
        && prepared.golden().is_file()
}

/// Write `build.toml`; `finished` is the completion time once Cargo succeeded.
pub(crate) fn write(
    request: &BuildRequest,
    prepared: &PreparedBuild,
    finished: Option<SystemTime>,
) -> Result<(), BuildError> {
    let path = prepared.dir.join(FILE);
    let generated = match (finished, read(&path)) {
        // Keep the generation time of the workspace this build finished from.
        (Some(_), Some(old)) if old.build_id == prepared.build_id => old.generated,
        _ => rfc3339(SystemTime::now()),
    };
    let meta = BuildMetadata {
        format: 1,
        build_id: prepared.build_id.clone(),
        environment: request.lock.environment.clone(),
        profile: request.profile.as_str().to_owned(),
        target: prepared.target.clone(),
        builder: BUILDER_VERSION.to_owned(),
        rustc: prepared.rustc.clone(),
        generated,
        finished: finished.map(rfc3339),
        pwc: PwcMetadata {
            source: request.pwc_source.display().to_string(),
            version: request.lock.pwc.version.to_string(),
            api: request.lock.pwc.api.to_string(),
            revision: request.lock.pwc.revision.clone(),
            dirty_digest: request.pwc_dirty_digest.clone(),
        },
        outputs: finished.map(|_| Outputs {
            game: format!("bin/{}", exe_name(GAME_BIN)),
            golden: format!("bin/{}", exe_name(GOLDEN_BIN)),
        }),
        package: request
            .lock
            .packages
            .iter()
            .map(|p| PackageMetadata {
                id: p.id.to_string(),
                version: p.version.to_string(),
                kind: p.kind.as_str().to_owned(),
                hash: p.hash.to_string(),
                dir: request
                    .packages
                    .get(&p.id)
                    .map(|(d, _)| d.display().to_string())
                    .unwrap_or_default(),
            })
            .collect(),
    };
    let body = toml::to_string(&meta)
        .map_err(|e| BuildError::Source(format!("cannot serialise {FILE}: {e}")))?;
    let text = format!("# Generated by pwc. Do not edit.\n{body}");
    let tmp = prepared.dir.join(format!(".{FILE}.tmp"));
    std::fs::write(&tmp, text).map_err(io_err(&tmp))?;
    std::fs::rename(&tmp, &path).map_err(io_err(&path))
}

fn read(path: &std::path::Path) -> Option<BuildMetadata> {
    toml::from_str(&std::fs::read_to_string(path).ok()?).ok()
}

/// `YYYY-MM-DDTHH:MM:SSZ` (UTC).
pub(crate) fn rfc3339(time: SystemTime) -> String {
    let secs = time.duration_since(UNIX_EPOCH).map_or(0, |d| d.as_secs());
    let (days, rem) = (secs / 86_400, secs % 86_400);
    let (y, m, d) = civil_from_days(days);
    format!(
        "{y:04}-{m:02}-{d:02}T{:02}:{:02}:{:02}Z",
        rem / 3600,
        rem % 3600 / 60,
        rem % 60
    )
}

/// Days since 1970-01-01 → (year, month, day) in the proleptic Gregorian calendar
/// (H. Hinnant's `civil_from_days`, restricted to non-negative days).
pub(crate) fn civil_from_days(days: u64) -> (u64, u64, u64) {
    let z = days + 719_468;
    let era = z / 146_097;
    let doe = z % 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = yoe + era * 400 + u64::from(m <= 2);
    (y, m, d)
}
