//! `pwc.lock` and the environment hash (docs/spec/instances.md).

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::manifest::parse_version;
use crate::text::{check_format, push_str_kv, quote_array, toml_error};
use crate::{FORMAT, ManifestError, ModKind, PackageHash, PackageId, Version};

/// The first line of every `pwc.lock`.
pub const LOCK_HEADER: &str = "# This file is generated by pwc. Do not edit it by hand.";

/// The pinned game source.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct LockedPwc {
    /// PWC game version.
    pub version: Version,
    /// `pwc-mod-api` version it provides.
    pub api: Version,
    /// Source checkout directory.
    pub source: PathBuf,
    /// Git revision, or `unknown`.
    pub revision: String,
    /// Uncommitted changes at lock time.
    pub dirty: bool,
}

/// Where a locked package came from.
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum PackageSource {
    /// `repository:<dir>` — a source directory or file inside a configured repository.
    Repository(PathBuf),
    /// `file:<path>` — an explicit `.pwcmod`.
    File(PathBuf),
    /// `path:<dir>` — a local, mutable source tree.
    Path(PathBuf),
    /// `store` — already installed, origin unknown.
    Store,
}

impl PackageSource {
    /// Parse the lock's text form: `repository:<dir>`, `file:<path>`, `path:<dir>` or `store`.
    pub fn parse(s: &str) -> Result<Self, ManifestError> {
        if s == "store" {
            return Ok(PackageSource::Store);
        }
        let invalid = |reason| ManifestError::invalid("source", s, reason);
        let (scheme, path) = s.split_once(':').ok_or_else(|| {
            invalid("must be `repository:<dir>`, `file:<path>`, `path:<dir>` or `store`")
        })?;
        if path.is_empty() {
            return Err(invalid("the path after the `:` is missing"));
        }
        let path = PathBuf::from(path);
        match scheme {
            "repository" => Ok(PackageSource::Repository(path)),
            "file" => Ok(PackageSource::File(path)),
            "path" => Ok(PackageSource::Path(path)),
            _ => Err(invalid(
                "must be `repository:<dir>`, `file:<path>`, `path:<dir>` or `store`",
            )),
        }
    }
}

/// The lock's text form (paths that are not UTF-8 are shown lossily).
impl std::fmt::Display for PackageSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PackageSource::Repository(path) => write!(f, "repository:{}", path.display()),
            PackageSource::File(path) => write!(f, "file:{}", path.display()),
            PackageSource::Path(path) => write!(f, "path:{}", path.display()),
            PackageSource::Store => f.write_str("store"),
        }
    }
}

/// One `[[package]]`.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct LockedPackage {
    /// Id.
    pub id: PackageId,
    /// Exact version.
    pub version: Version,
    /// Kind.
    pub kind: ModKind,
    /// Content hash (the store key).
    pub hash: PackageHash,
    /// Origin.
    pub source: PackageSource,
    /// Dependency ids, sorted.
    pub dependencies: Vec<PackageId>,
}

/// A parsed `pwc.lock`.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Lockfile {
    /// The game source.
    pub pwc: LockedPwc,
    /// Packages sorted by id.
    pub packages: Vec<LockedPackage>,
    /// Environment hash as recorded (verified on parse).
    pub environment: String,
}

impl Lockfile {
    /// Build a lockfile (sorts packages and dependencies, computes the environment).
    ///
    /// Duplicate dependency ids are removed. The caller (the resolver) provides one entry per id
    /// and an entry for every dependency; a lock breaking that is rejected by [`Lockfile::parse`].
    pub fn new(pwc: LockedPwc, mut packages: Vec<LockedPackage>) -> Self {
        packages.sort_by(|a, b| a.id.cmp(&b.id));
        for package in &mut packages {
            package.dependencies.sort();
            package.dependencies.dedup();
        }
        let environment = environment_hash(&pwc, &packages);
        Self {
            pwc,
            packages,
            environment,
        }
    }

    /// Parse; rejects a lock whose recorded environment does not match its contents.
    ///
    /// Also rejects a lock that is not in canonical order (packages sorted by id without
    /// duplicates, each dependency list sorted without duplicates) or that names a dependency
    /// without its own `[[package]]` entry.
    pub fn parse(text: &str) -> Result<Self, ManifestError> {
        check_format(text)?;
        let raw: RawLock = toml::from_str(text).map_err(toml_error)?;
        raw.validate()
    }

    /// Read a file.
    pub fn from_file(path: &Path) -> Result<Self, ManifestError> {
        let text = std::fs::read_to_string(path).map_err(|source| ManifestError::Io {
            path: path.to_path_buf(),
            source,
        })?;
        Self::parse(&text)
    }

    /// Canonical text, starting with the "generated, do not edit" comment.
    pub fn to_toml_string(&self) -> String {
        let mut out = String::new();
        let _ = writeln!(out, "{LOCK_HEADER}");
        let _ = writeln!(out, "format = {FORMAT}");
        push_str_kv(&mut out, "environment", &self.environment);
        out.push_str("\n[pwc]\n");
        push_str_kv(&mut out, "version", &self.pwc.version.to_string());
        push_str_kv(&mut out, "api", &self.pwc.api.to_string());
        push_str_kv(&mut out, "source", &self.pwc.source.to_string_lossy());
        push_str_kv(&mut out, "revision", &self.pwc.revision);
        let _ = writeln!(out, "dirty = {}", self.pwc.dirty);
        for package in &self.packages {
            out.push_str("\n[[package]]\n");
            push_str_kv(&mut out, "id", package.id.as_str());
            push_str_kv(&mut out, "version", &package.version.to_string());
            push_str_kv(&mut out, "kind", package.kind.as_str());
            push_str_kv(&mut out, "hash", package.hash.as_str());
            push_str_kv(&mut out, "source", &package.source.to_string());
            let _ = writeln!(
                out,
                "dependencies = {}",
                quote_array(package.dependencies.iter().map(PackageId::as_str))
            );
        }
        out
    }

    /// Recompute the environment hash from the contents (what [`Lockfile::parse`] checks).
    pub fn computed_environment(&self) -> String {
        environment_hash(&self.pwc, &self.packages)
    }

    /// The entry for `id`.
    pub fn package(&self, id: &PackageId) -> Option<&LockedPackage> {
        self.packages.iter().find(|p| &p.id == id)
    }
}

/// The environment hash of a lock's contents (docs/spec/instances.md, "Environment hash"):
/// `sha256:<hex>` of the environment text, with the packages taken in the order given (lock order).
pub fn environment_hash(pwc: &LockedPwc, packages: &[LockedPackage]) -> String {
    let digest: [u8; 32] = Sha256::digest(environment_text(pwc, packages).as_bytes()).into();
    PackageHash::from_digest(digest).into()
}

/// The text the environment hash is computed over:
///
/// ```text
/// pwc-environment 1
/// pwc <version> <revision> <dirty: 0|1> api <api>
/// package <id> <version> <kind> <hash> deps <dep1>,<dep2>
/// ```
///
/// with `\n` after every line. A package without dependencies ends in `deps ` (the empty list).
fn environment_text(pwc: &LockedPwc, packages: &[LockedPackage]) -> String {
    let mut text = String::from("pwc-environment 1\n");
    let _ = writeln!(
        text,
        "pwc {} {} {} api {}",
        pwc.version,
        pwc.revision,
        u8::from(pwc.dirty),
        pwc.api
    );
    for p in packages {
        let deps: Vec<&str> = p.dependencies.iter().map(PackageId::as_str).collect();
        let _ = writeln!(
            text,
            "package {} {} {} {} deps {}",
            p.id,
            p.version,
            p.kind.as_str(),
            p.hash,
            deps.join(",")
        );
    }
    text
}

/// `pwc.lock` as written, before validation.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawLock {
    /// Checked by [`check_format`] before deserialising.
    #[serde(rename = "format")]
    _format: serde::de::IgnoredAny,
    environment: Option<String>,
    pwc: Option<RawPwc>,
    package: Option<Vec<RawPackage>>,
}

/// `[pwc]` as written.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawPwc {
    version: Option<String>,
    api: Option<String>,
    source: Option<String>,
    revision: Option<String>,
    dirty: Option<bool>,
}

/// One `[[package]]` as written.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawPackage {
    id: Option<String>,
    version: Option<String>,
    kind: Option<String>,
    hash: Option<String>,
    source: Option<String>,
    dependencies: Option<Vec<String>>,
}

impl RawLock {
    fn validate(self) -> Result<Lockfile, ManifestError> {
        let environment = self
            .environment
            .ok_or(ManifestError::Missing("environment"))?;
        let pwc = self.pwc.ok_or(ManifestError::Missing("pwc"))?.validate()?;
        let packages = self
            .package
            .unwrap_or_default()
            .into_iter()
            .enumerate()
            .map(|(i, p)| p.validate(i))
            .collect::<Result<Vec<_>, _>>()?;

        for (i, pair) in packages.windows(2).enumerate() {
            if pair[0].id >= pair[1].id {
                let reason = if pair[0].id == pair[1].id {
                    "listed twice"
                } else {
                    "packages must be sorted by id"
                };
                return Err(ManifestError::invalid(
                    format!("package[{}].id", i + 1),
                    pair[1].id.as_str(),
                    reason,
                ));
            }
        }
        for (i, package) in packages.iter().enumerate() {
            for dep in &package.dependencies {
                if packages.binary_search_by(|p| p.id.cmp(dep)).is_err() {
                    return Err(ManifestError::invalid(
                        format!("package[{i}].dependencies"),
                        dep.as_str(),
                        "has no [[package]] entry of its own",
                    ));
                }
            }
        }

        let computed = environment_hash(&pwc, &packages);
        if environment != computed {
            return Err(ManifestError::invalid(
                "environment",
                environment,
                format!(
                    "does not match the lock contents (they hash to {computed}); regenerate the lock with `pwc lock`"
                ),
            ));
        }
        Ok(Lockfile {
            pwc,
            packages,
            environment,
        })
    }
}

impl RawPwc {
    fn validate(self) -> Result<LockedPwc, ManifestError> {
        let version = self.version.ok_or(ManifestError::Missing("pwc.version"))?;
        let version = Version::parse(&version).map_err(|e| {
            ManifestError::invalid(
                "pwc.version",
                version.as_str(),
                format!("not a SemVer version ({e})"),
            )
        })?;
        let api = self.api.ok_or(ManifestError::Missing("pwc.api"))?;
        let api = Version::parse(&api).map_err(|e| {
            ManifestError::invalid(
                "pwc.api",
                api.as_str(),
                format!("not a SemVer version ({e})"),
            )
        })?;
        let source = self.source.ok_or(ManifestError::Missing("pwc.source"))?;
        if source.is_empty() {
            return Err(ManifestError::invalid(
                "pwc.source",
                source,
                "must not be empty",
            ));
        }
        let revision = self
            .revision
            .ok_or(ManifestError::Missing("pwc.revision"))?;
        if revision.is_empty() || revision.contains(|c: char| c.is_whitespace() || c.is_control()) {
            return Err(ManifestError::invalid(
                "pwc.revision",
                revision,
                "must be a git revision or `unknown` (no spaces)",
            ));
        }
        let dirty = self.dirty.ok_or(ManifestError::Missing("pwc.dirty"))?;
        Ok(LockedPwc {
            version,
            api,
            source: PathBuf::from(source),
            revision,
            dirty,
        })
    }
}

impl RawPackage {
    fn validate(self, index: usize) -> Result<LockedPackage, ManifestError> {
        let key = |field: &str| format!("package[{index}].{field}");
        let id = PackageId::parse_as(
            &self.id.ok_or(ManifestError::Missing("package.id"))?,
            &key("id"),
        )?;
        let version = parse_version(
            &key("version"),
            &self
                .version
                .ok_or(ManifestError::Missing("package.version"))?,
        )?;
        let kind = self.kind.ok_or(ManifestError::Missing("package.kind"))?;
        let kind = ModKind::from_name(&kind).ok_or_else(|| {
            ManifestError::invalid(
                key("kind"),
                kind.as_str(),
                "must be \"mod\", \"library\" or \"bundle\"",
            )
        })?;
        let hash = self.hash.ok_or(ManifestError::Missing("package.hash"))?;
        let hash = PackageHash::parse(&hash).map_err(|err| rekey(err, &key("hash")))?;
        let source = self
            .source
            .ok_or(ManifestError::Missing("package.source"))?;
        let source = PackageSource::parse(&source).map_err(|err| rekey(err, &key("source")))?;
        let mut dependencies = Vec::new();
        for dep in self
            .dependencies
            .ok_or(ManifestError::Missing("package.dependencies"))?
        {
            let dep = PackageId::parse_as(&dep, &key("dependencies"))?;
            if dep == id {
                return Err(ManifestError::invalid(
                    key("dependencies"),
                    dep.as_str(),
                    "a package cannot depend on itself",
                ));
            }
            if let Some(last) = dependencies.last()
                && *last >= dep
            {
                let reason = if *last == dep {
                    "listed twice"
                } else {
                    "dependencies must be sorted"
                };
                return Err(ManifestError::invalid(
                    key("dependencies"),
                    dep.as_str(),
                    reason,
                ));
            }
            dependencies.push(dep);
        }
        Ok(LockedPackage {
            id,
            version,
            kind,
            hash,
            source,
            dependencies,
        })
    }
}

/// Replace the key of an [`ManifestError::Invalid`] (helpers name a generic key like `hash`).
fn rekey(err: ManifestError, key: &str) -> ManifestError {
    match err {
        ManifestError::Invalid { value, reason, .. } => ManifestError::Invalid {
            key: key.to_string(),
            value,
            reason,
        },
        other => other,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn id(s: &str) -> PackageId {
        PackageId::parse(s).unwrap()
    }

    fn hash(byte: u8) -> PackageHash {
        PackageHash::from_digest([byte; 32])
    }

    fn pwc() -> LockedPwc {
        LockedPwc {
            version: Version::new(2, 1, 0),
            api: Version::new(1, 0, 0),
            source: "/home/alice/src/project_watt_cubed".into(),
            revision: "ec10f7186cf1".into(),
            dirty: false,
        }
    }

    fn package(name: &str, deps: &[&str], byte: u8) -> LockedPackage {
        LockedPackage {
            id: id(name),
            version: Version::new(1, 0, 0),
            kind: ModKind::Mod,
            hash: hash(byte),
            source: PackageSource::Repository(format!("/repo/mods/{name}").into()),
            dependencies: deps.iter().map(|d| id(d)).collect(),
        }
    }

    fn sample() -> Lockfile {
        Lockfile::new(
            pwc(),
            vec![
                package("pwc.inventory", &["pwc.hotbar"], 0xc1),
                package("pwc.hotbar", &[], 0x73),
            ],
        )
    }

    #[test]
    fn new_sorts_and_dedups() {
        let lock = Lockfile::new(
            pwc(),
            vec![
                package("z.z", &["b.b", "a.a", "b.b"], 1),
                package("a.a", &[], 2),
                package("b.b", &["a.a"], 3),
            ],
        );
        let ids: Vec<&str> = lock.packages.iter().map(|p| p.id.as_str()).collect();
        assert_eq!(ids, ["a.a", "b.b", "z.z"]);
        assert_eq!(lock.packages[2].dependencies, [id("a.a"), id("b.b")]);
        assert_eq!(lock.environment, lock.computed_environment());
        assert_eq!(lock.package(&id("b.b")).unwrap().hash, hash(3));
        assert!(lock.package(&id("c.c")).is_none());
    }

    #[test]
    fn environment_hash_is_the_spec_text() {
        let lock = sample();
        let text = format!(
            "pwc-environment 1\npwc 2.1.0 ec10f7186cf1 0 api 1.0.0\npackage pwc.hotbar 1.0.0 mod {} deps \npackage pwc.inventory 1.0.0 mod {} deps pwc.hotbar\n",
            hash(0x73),
            hash(0xc1)
        );
        assert_eq!(environment_text(&lock.pwc, &lock.packages), text);
        let digest: [u8; 32] = Sha256::digest(text.as_bytes()).into();
        assert_eq!(
            lock.environment,
            String::from(PackageHash::from_digest(digest))
        );
    }

    #[test]
    fn environment_hash_golden_value() {
        // Pinned (computed independently with Python's hashlib over the spec text): changing the
        // environment text format changes every environment in the wild.
        assert_eq!(
            sample().environment,
            "sha256:405a7fa505ad5c901418e0523446d4c13edd0807407c6bc824af67995b4c2589"
        );
    }

    #[test]
    fn environment_depends_on_build_inputs_only() {
        let base = sample();
        let mut moved = base.clone();
        moved.pwc.source = "/elsewhere/pwc".into();
        moved.packages[0].source = PackageSource::Store;
        assert_eq!(
            moved.computed_environment(),
            base.environment,
            "paths do not change the environment"
        );

        let mut variants = Vec::new();
        let mut v = base.clone();
        v.pwc.dirty = true;
        variants.push(v);
        let mut v = base.clone();
        v.pwc.revision = "unknown".into();
        variants.push(v);
        let mut v = base.clone();
        v.pwc.version = Version::new(2, 1, 1);
        variants.push(v);
        let mut v = base.clone();
        v.pwc.api = Version::new(1, 1, 0);
        variants.push(v);
        let mut v = base.clone();
        v.packages[0].hash = hash(0);
        variants.push(v);
        let mut v = base.clone();
        v.packages[0].kind = ModKind::Library;
        variants.push(v);
        let mut v = base.clone();
        v.packages[1].dependencies.clear();
        variants.push(v);
        let mut v = base.clone();
        v.packages[1].version = Version::parse("1.0.0-rc.1").unwrap();
        variants.push(v);
        for v in variants {
            assert_ne!(v.computed_environment(), base.environment, "{v:?}");
        }
    }

    #[test]
    fn canonical_text() {
        let lock = sample();
        let expected = format!(
            r#"# This file is generated by pwc. Do not edit it by hand.
format = 1
environment = "{}"

[pwc]
version = "2.1.0"
api = "1.0.0"
source = "/home/alice/src/project_watt_cubed"
revision = "ec10f7186cf1"
dirty = false

[[package]]
id = "pwc.hotbar"
version = "1.0.0"
kind = "mod"
hash = "{}"
source = "repository:/repo/mods/pwc.hotbar"
dependencies = []

[[package]]
id = "pwc.inventory"
version = "1.0.0"
kind = "mod"
hash = "{}"
source = "repository:/repo/mods/pwc.inventory"
dependencies = ["pwc.hotbar"]
"#,
            lock.environment,
            hash(0x73),
            hash(0xc1)
        );
        assert_eq!(lock.to_toml_string(), expected);
        assert!(lock.to_toml_string().starts_with(LOCK_HEADER));
    }

    #[test]
    fn round_trips() {
        let mut packages = vec![
            package("a.lib", &[], 1),
            package("b.mod", &["a.lib"], 2),
            package("c.bundle", &["a.lib", "b.mod"], 3),
            package("d.local", &[], 4),
            package("e.file", &[], 5),
        ];
        packages[0].kind = ModKind::Library;
        packages[2].kind = ModKind::Bundle;
        packages[2].source = PackageSource::Store;
        packages[3].source = PackageSource::Path("/home/me/dev/d local".into());
        packages[4].source = PackageSource::File("/downloads/e.file-1.0.0.pwcmod".into());
        packages[4].version = Version::parse("3.0.0-beta.2").unwrap();
        let mut p = pwc();
        p.dirty = true;
        p.revision = "unknown".into();
        let lock = Lockfile::new(p, packages);
        let text = lock.to_toml_string();
        let back = Lockfile::parse(&text).unwrap_or_else(|e| panic!("{e}\n{text}"));
        assert_eq!(back, lock);
        assert_eq!(back.to_toml_string(), text);

        let empty = Lockfile::new(pwc(), Vec::new());
        assert_eq!(Lockfile::parse(&empty.to_toml_string()).unwrap(), empty);
    }

    #[test]
    fn tampering_is_detected() {
        let text = sample().to_toml_string();
        let edited = text.replace(
            "version = \"1.0.0\"\nkind = \"mod\"",
            "version = \"1.0.1\"\nkind = \"mod\"",
        );
        assert_ne!(edited, text);
        let err = Lockfile::parse(&edited).unwrap_err();
        assert!(
            matches!(&err, ManifestError::Invalid { key, .. } if key == "environment"),
            "{err}"
        );

        let flipped = text.replace("dirty = false", "dirty = true");
        assert!(
            matches!(Lockfile::parse(&flipped), Err(ManifestError::Invalid { key, .. }) if key == "environment")
        );

        // Paths are not part of the environment: moving the source keeps the lock valid.
        let moved = text.replace(
            "source = \"/home/alice/src/project_watt_cubed\"",
            "source = \"/opt/pwc\"",
        );
        assert!(Lockfile::parse(&moved).is_ok());
    }

    /// The text of a lock with exactly these packages, in this order, and a correct environment
    /// (bypassing [`Lockfile::new`]'s sorting), so only the structural rule under test fails.
    fn raw_text(packages: Vec<LockedPackage>) -> String {
        let pwc = pwc();
        let environment = environment_hash(&pwc, &packages);
        Lockfile {
            pwc,
            packages,
            environment,
        }
        .to_toml_string()
    }

    #[test]
    fn structure_is_checked() {
        let a = package("a.a", &[], 1);
        let b = package("b.b", &["a.a"], 2);
        let text = raw_text(vec![a.clone(), b.clone()]);
        assert!(Lockfile::parse(&text).is_ok());

        // Unsorted packages.
        let err = Lockfile::parse(&raw_text(vec![b.clone(), a.clone()])).unwrap_err();
        assert!(
            matches!(&err, ManifestError::Invalid { key, reason, .. } if key == "package[1].id" && reason.contains("sorted")),
            "{err}"
        );

        // Duplicate packages.
        let err = Lockfile::parse(&raw_text(vec![a.clone(), a.clone()])).unwrap_err();
        assert!(err.to_string().contains("listed twice"), "{err}");

        // Dependency without an entry.
        let err = Lockfile::parse(&raw_text(vec![b.clone()])).unwrap_err();
        assert!(
            matches!(&err, ManifestError::Invalid { key, .. } if key == "package[0].dependencies"),
            "{err}"
        );

        // Unsorted, duplicate and self dependencies.
        for (deps, message) in [
            (&["b.b", "a.a"][..], "sorted"),
            (&["a.a", "a.a"][..], "twice"),
            (&["a.a", "c.c"][..], "itself"),
        ] {
            let c = package("c.c", deps, 3);
            let err = Lockfile::parse(&raw_text(vec![a.clone(), b.clone(), c])).unwrap_err();
            assert!(
                matches!(&err, ManifestError::Invalid { key, .. } if key == "package[2].dependencies"),
                "{err}"
            );
            assert!(err.to_string().contains(message), "{err}");
        }

        // Field validation names the entry.
        for (from, to, key) in [
            ("kind = \"mod\"", "kind = \"plugin\"", "package[0].kind"),
            ("id = \"a.a\"", "id = \"A\"", "package[0].id"),
            (
                "source = \"repository:/repo/mods/a.a\"",
                "source = \"git:/x\"",
                "package[0].source",
            ),
            (
                "source = \"repository:/repo/mods/a.a\"",
                "source = \"file:\"",
                "package[0].source",
            ),
            (
                "revision = \"ec10f7186cf1\"",
                "revision = \"two words\"",
                "pwc.revision",
            ),
            ("version = \"2.1.0\"", "version = \"2.1\"", "pwc.version"),
        ] {
            let edited = text.replacen(from, to, 1);
            assert_ne!(edited, text, "{from}");
            match Lockfile::parse(&edited) {
                Err(ManifestError::Invalid { key: k, .. }) if k == key => {}
                other => panic!("{to}: expected invalid `{key}`, got {other:?}"),
            }
        }
        let bad_hash = text.replacen(hash(1).as_str(), "sha256:XYZ", 1);
        assert!(
            matches!(Lockfile::parse(&bad_hash), Err(ManifestError::Invalid { key, .. }) if key == "package[0].hash")
        );
        let bad_version = text.replacen("version = \"1.0.0\"", "version = \"1.0.0+meta\"", 1);
        assert!(
            matches!(Lockfile::parse(&bad_version), Err(ManifestError::Invalid { key, .. }) if key == "package[0].version")
        );

        // Missing and unknown keys.
        assert!(matches!(
            Lockfile::parse(&text.replace("dirty = false\n", "")),
            Err(ManifestError::Missing("pwc.dirty"))
        ));
        assert!(matches!(
            Lockfile::parse(&text.replacen("dependencies = []\n", "", 1)),
            Err(ManifestError::Missing("package.dependencies"))
        ));
        assert!(matches!(
            Lockfile::parse(&text.replace("[pwc]", "[pwc]\nextra = 1")),
            Err(ManifestError::Toml(_))
        ));
        assert!(matches!(
            Lockfile::parse("format = 1\n[pwc]\n"),
            Err(ManifestError::Missing("environment"))
        ));
        assert!(matches!(
            Lockfile::parse("format = 2\n"),
            Err(ManifestError::Format { found: 2 })
        ));
    }

    #[test]
    fn package_source_text() {
        for (text, source) in [
            (
                "repository:/repo/mods/hotbar",
                PackageSource::Repository("/repo/mods/hotbar".into()),
            ),
            (
                "file:/downloads/a.b-1.0.0.pwcmod",
                PackageSource::File("/downloads/a.b-1.0.0.pwcmod".into()),
            ),
            ("path:../dev/x:y", PackageSource::Path("../dev/x:y".into())),
            ("store", PackageSource::Store),
        ] {
            assert_eq!(PackageSource::parse(text).unwrap(), source);
            assert_eq!(source.to_string(), text);
        }
        for bad in [
            "",
            "store:",
            "repository",
            "repository:",
            "git:/x",
            "Store",
            "/plain/path",
        ] {
            assert!(PackageSource::parse(bad).is_err(), "{bad}");
        }
    }
}
